server:
  port : 8083
  servlet:
    context-path: /auth-service

spring:

  application:
    name: auth-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3308/auth_service_dev_db}
    username: ${DATABASE_UER:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

security:
  jwt: 
    token: 
      secret-key: ${JWT_SECRET_KEY:linecode}
      expire-timeout: 360000


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/discovery-service/eureka/}

admin:
  username: admin
  password: admin##!
  rule: admin