version: '3'
services:

## Discovery Service
  discovery_service_app:
    build:
      context: ./
      dockerfile: ./discovery-service.dockerfile
    image: discovery_service_app
    container_name: discovery_service_app
    ports: 
      - 8761:8761
    expose:
      - "8761"
    networks:
      spring_cloud_net:
        ipv4_address: 172.28.1.1

## Gateway Service
  gateway_service_app:
    build:
      context: ./
      dockerfile: ./gateway-service.dockerfile
    image: gateway_service_app
    container_name: gateway_service_app
    ports: 
      - 8080:8080
    depends_on:
      - discovery_service_app
    environment:
      - EUREKA_SERVER=http://172.28.1.1:8761/discovery-service/eureka/
    links:
      - auth_service_app
      - product_service_app
    expose:
      - "8080"
    networks:
      spring_cloud_net:
      
## Auth Service
  #DB
  auth_service_db:
    environment:
        - MYSQL_ROOT_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
        - MYSQL_DATABASE=${AUTH_SERVICE_DB_NAME}
    image: mysql:5.7
    container_name: auth_service_db
    ports:
      - ${AUTH_SERVICE_DB_PORT}:3306
    volumes:
      - ${AUTH_SERVICE_DB_PATH}:/var/lib/mysql
    expose:
      - "3306"
    networks:
      spring_cloud_net:

  #APP
  auth_service_app:
    build:
      context: ./
      dockerfile: ./auth-service.dockerfile
    image: auth_service_app
    container_name: auth_service_app
    ports: 
      - "8083:8083"
    expose:
      - "8083"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EUREKA_SERVER=http://172.28.1.1:8761/discovery-service/eureka/
      - DATABASE_URL=jdbc:mysql://auth_service_db:3306/${AUTH_SERVICE_DB_NAME}
      - DATABASE_UER=${AUTH_SERVICE_DB_USER}
      - DATABASE_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
    depends_on:
      - auth_service_db
      - discovery_service_app
    networks:
      spring_cloud_net:

## Product Service
  #DB
  product_service_db:
    environment:
      - MYSQL_ROOT_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - MYSQL_DATABASE=${PRODUCT_SERVICE_DB_NAME}
    image: mysql:5.7
    container_name: product_service_db
    ports:
      - ${PRODUCT_SERVICE_DB_PORT}:3306 
    volumes:
      - ${PRODUCT_SERVICE_DB_PATH}:/var/lib/mysql
    expose:
      - "3306"
    networks:
      spring_cloud_net:
    
  #APP
  product_service_app:
    build:
      context: ./
      dockerfile: ./product-service.dockerfile
    image: product_service_app
    container_name: product_service_app
    ports: 
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EUREKA_SERVER=http://172.28.1.1:8761/discovery-service/eureka/
      - DATABASE_URL=jdbc:mysql://product_service_db:3306/${PRODUCT_SERVICE_DB_NAME}
      - DATABASE_UER=${PRODUCT_SERVICE_DB_USER}
      - DATABASE_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
    depends_on:
      - product_service_db
      - discovery_service_app
    networks:
      spring_cloud_net:

networks:
  spring_cloud_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16