version: '3.6'

services:
  
  product_service_dev_db:
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=product_service_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - '3306:3306'
    volumes:
      - ${PRODUCT_SERVICE_DB_PATH}:/var/lib/mysql
