version: '3.6'

services:
  
  product_service_dev_db:
    environment:
        - MYSQL_ROOT_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
        - MYSQL_DATABASE=${PRODUCT_SERVICE_DB_NAME}
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - ${PRODUCT_SERVICE_DB_PORT}:3306
    volumes:
      - ${PRODUCT_SERVICE_DB_PATH}:/var/lib/mysql

  payment_service_dev_db:
    environment:
        - MYSQL_ROOT_PASSWORD=${PAYMENT_SERVICE_DB_PASSWORD}
        - MYSQL_DATABASE=${PAYMENT_SERVICE_DB_NAME}
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - ${PAYMENT_SERVICE_DB_PORT}:3306
    volumes:
      - ${PAYMENT_SERVICE_DB_PATH}:/var/lib/mysql


  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
     - ${RABBITMQ_PATH}:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
     - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}