server:
  port : 8080
  servlet:
    context-path: /product-service

spring:
  
  application:
    name: product-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product_service_db
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mqadmin
    password: mqadmin


eureka:

  instance: 
    hostname: localhost
 
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery-service/eureka/

product:
  amqp:
    exchange: product.exchange
    routingkey:
        create: queue.create
        delete: queue.delete
        update: queue.update
        