server:
  port : 8081
  servlet:
    context-path: /product-service

spring:
  
  profiles:
    active: dev

  application:
    name: product-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3308/product_service_db}
    username: ${DATABASE_UER:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:mqadmin}
    password: ${RABBITMQ_PASSWORD:mqadmin}

security:
  jwt: 
    token: 
      secret-key: ${JWT_SECRET_KEY:linecode}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/discovery-service/eureka/}

product:
  amqp:
    exchange: product.exchange
    routingkey:
        create: queue.create
        delete: queue.delete
        update: queue.update
        